/*
	THESAURUS_RELATIONSHIP.C
	------------------------
*/
#include "thesaurus_relationship.h"

char *ANT_thesaurus_relationship::name_of_relationship[] = 
{
"MEMBER_OF_TOPIC",
"MEMBER_OF_REGION",
"MEMBER_OF_USAGE",
"HYPONYM",
"INSTANCE_HYPONYM",
"ANTONYM",
"MEMBER_HOLONYM",
"PART_HOLONYM",
"SUBSTANCE_HOLONYM",
"VERB_GROUP",
"MEMBER_MERONYM",
"PART_MERONYM",
"SUBSTANCE_MERONYM",
"SIMILAR_TO",
"ENTAILMENT",
"DOMAIN_OF_TOPIC",
"DOMAIN_OF_REGION",
"DOMAIN_OF_USAGE",
"HYPERNYM",
"INSTANCE_HYPERNYM",
"FROM_ABJECTIVE",
"PERTAINYM",
"SEE_ALSO",
"DERIVED_FORM",
"PRINCIPLE_OF_VERB",
"ATTRIBUTE",
"CAUSE",
"SYNONYM",
"SENTINAL"
} ;

